// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtapupr20yg0hXb-_7j6-PDfzQvwGpo-4',
    appId: '1:506282016615:web:8421292ea1d10ee2c6f9c2',
    messagingSenderId: '506282016615',
    projectId: 'fir-project-8f50b',
    authDomain: 'fir-project-8f50b.firebaseapp.com',
    storageBucket: 'fir-project-8f50b.firebasestorage.app',
    measurementId: 'G-4T58NTNG02',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU0Jm4FxYhczGm0EbRpSJlnkOHKyypMOc',
    appId: '1:506282016615:android:c057f588434e0fb4c6f9c2',
    messagingSenderId: '506282016615',
    projectId: 'fir-project-8f50b',
    storageBucket: 'fir-project-8f50b.firebasestorage.app',
  );
}
